export const SECTIONS = [
  { id: 0, name: 'Personal Protective Equipment', short: 'PPE', icon: '🦺', color: '#B07D10' },
  { id: 1, name: 'Traffic Safety', short: 'Traffic', icon: '🚦', color: '#A04010' },
  { id: 2, name: 'Alcohol & Drug-Free Workplace', short: 'Substances', icon: '⚠️', color: '#7B2B2B' },
  { id: 3, name: 'Hazardous Chemicals', short: 'Chemicals', icon: '⚗️', color: '#4A3E8C' },
  { id: 4, name: 'Machine Safety & Lockout/Tagout', short: 'Machinery', icon: '⚙️', color: '#1A5C2A' },
  { id: 5, name: 'Permit to Work', short: 'Permits', icon: '📋', color: '#1A4F8A' },
  { id: 6, name: 'Emergency Procedures', short: 'Emergency', icon: '🚨', color: '#C0392B' },
];

export const QUESTIONS = [
  { s:0, q:'When should PPE be worn in the facility?', o:['Only when a supervisor is watching','At all times in designated areas','Only during heavy lifting tasks','Only during the first week of work'], a:1, e:'PPE must be worn at all times in designated areas, regardless of task duration or supervision.' },
  { s:0, q:"You're entering a production area for 'just 5 minutes'. Your helmet and glasses are at your station. What should you do?", o:['Enter quickly and be careful','Ask someone to watch from outside','Get the PPE before entering — no exceptions','Enter only if it\'s an emergency'], a:2, e:'There are no exceptions to PPE requirements — always retrieve your PPE before entering a production area.' },
  { s:0, q:'Which of the following is NOT considered PPE?', o:['Safety helmet','Steel-toed boots','Company uniform','High-visibility vest'], a:2, e:'A company uniform is not PPE. PPE includes helmets, boots, gloves, goggles, and high-visibility vests.' },
  { s:0, q:'What should you do if your PPE is damaged?', o:['Continue using it carefully','Tape it up temporarily','Leave it at your station','Report and replace it immediately'], a:3, e:'Damaged PPE must be reported and replaced immediately — it cannot provide adequate protection.' },
  { s:0, q:'A visitor is wearing only a hairnet in a production zone. What should you do?', o:['Ignore it — they\'re just visiting','Warn the visitor and report to a supervisor immediately','Wait to see if a supervisor notices','Only intervene if they touch equipment'], a:1, e:'Everyone in a production zone must wear proper PPE. Warn the visitor and report to a supervisor.' },
  { s:1, q:'Who has the right of way inside the factory premises?', o:['Employees on foot','Supervisors and managers','Forklifts and moving vehicles','Whoever arrives first'], a:2, e:'Forklifts and moving vehicles always have the right of way. Pedestrians must yield and use designated walkways.' },
  { s:1, q:'Before crossing a vehicle pathway inside the plant, you should:', o:['Run quickly across','Make eye contact with drivers and look both ways','Wait for traffic lights','Wave at the forklift driver and walk across'], a:1, e:'Always make eye contact with vehicle operators and look both ways before crossing — never assume you\'ve been seen.' },
  { s:1, q:'Where should pedestrians walk inside the plant?', o:['Anywhere that is convenient','On the side of vehicle lanes','On marked pedestrian walkways','In groups for added safety'], a:2, e:'Pedestrians must only walk on clearly marked pedestrian walkways to stay safe from vehicle traffic.' },
  { s:2, q:'It is acceptable to enter the workplace under the influence of alcohol or drugs if you\'re not operating machines.', o:['True — only machine operators need to be sober','True — in small amounts it is fine','False — it is strictly prohibited at all times','True — only if you feel fine'], a:2, e:'Being under the influence is strictly prohibited at all times — no exceptions, regardless of role.' },
  { s:2, q:'Why is sobriety important in a workplace?', o:['It is a legal requirement only','It ensures alertness and safety for yourself and others','It reduces the cost of insurance','Management prefers it'], a:1, e:'Sobriety is essential because alcohol and drugs impair judgment, reaction time, and decision-making.' },
  { s:2, q:'A coworker has bloodshot eyes and is behaving oddly but still working. What should you do first?', o:['Ignore it and focus on your work','Tell other colleagues about it','Confront them publicly','Immediately report to the supervisor'], a:3, e:'Report suspected impairment to a supervisor immediately — this protects everyone in the facility.' },
  { s:3, q:'What document should you read before handling any chemical?', o:['Employee handbook','Safety Data Sheet (SDS)','Company newsletter','Production schedule'], a:1, e:'Always consult the Safety Data Sheet (SDS/MSDS) before handling any chemical.' },
  { s:3, q:'Which PPE is essential when handling hazardous chemicals?', o:['Hard hat and boots only','Gloves and goggles','High-visibility vest only','Earmuffs and gloves'], a:1, e:'Chemical handling requires gloves and goggles at minimum to protect skin and eyes.' },
  { s:3, q:'A label on a chemical is worn off but you recognise the container. What do you do?', o:['Use it carefully — you know what it is','Ask a colleague to confirm and proceed','Stop and request re-labeling and SDS check','Use it only for a quick task'], a:2, e:'Never use an unlabeled chemical. Request proper re-labeling and verify the SDS before proceeding.' },
  { s:3, q:'If a chemical splashes on your skin, what is your first action?', o:['Wipe it off and continue working','Apply a bandage','Immediately rinse with water for at least 15 minutes','Report to the office first'], a:2, e:'Immediately rinse affected skin with large amounts of water for at least 15 minutes, then seek medical attention.' },
  { s:4, q:"It's okay to bypass a safety guard if it slows down your task.", o:['True — efficiency is important','True — only if your supervisor approves','False — safety guards must never be bypassed','True — for experienced workers only'], a:2, e:'Safety guards must NEVER be bypassed. They protect against serious injury — no task is worth overriding them.' },
  { s:4, q:'What is the purpose of a Lockout/Tagout procedure?', o:['To log machine downtime','To schedule maintenance windows','To ensure machines are completely shut down before maintenance','To notify the production team of repairs'], a:2, e:'Lockout/Tagout ensures machines are completely de-energized and cannot be accidentally started during maintenance.' },
  { s:4, q:'Who is allowed to perform machine maintenance?', o:['Any employee in the area','Only trained and authorized personnel','The most experienced person nearby','Anyone if the machine is switched off'], a:1, e:'Only trained and authorized personnel may perform machine maintenance — after applying full Lockout/Tagout procedures.' },
  { s:5, q:'Which of the following requires a Permit to Work?', o:['Routine cleaning of office floors','Hot work, confined space entry, and working at height','Daily machine inspection','Replacing PPE equipment'], a:1, e:'High-risk tasks — hot work, confined space entry, and working at height — all require a Permit to Work.' },
  { s:5, q:'A Permit to Work ensures:', o:['Faster task completion','Reduced paperwork','Hazards are identified and controls are in place before work begins','Only senior staff can supervise'], a:2, e:'A Permit to Work ensures all hazards are identified and controls are in place before high-risk work begins.' },
  { s:5, q:'Who approves a Permit to Work?', o:['The worker performing the task','Any available colleague','The safety officer or authorized issuer','The production manager only'], a:2, e:'Permits to Work must be approved by a qualified safety officer or authorized issuer — never self-authorize.' },
  { s:6, q:'What is the first thing to do if a fire alarm sounds?', o:['Continue working until you see smoke','Call a colleague to confirm the alarm','Stop work immediately and follow the evacuation plan','Look for the fire before leaving'], a:2, e:'When a fire alarm sounds, stop work immediately and follow the evacuation plan — do not investigate.' },
  { s:6, q:'Emergency exits and fire extinguishers should be:', o:['Locked to prevent misuse','Used for storage when not needed','Accessible at all times and clearly marked','Checked only during annual audits'], a:2, e:'Emergency exits and fire extinguishers must always be accessible, clearly marked, and never blocked.' },
  { s:6, q:'During an emergency drill, what should a guest do?', o:['Stay in the meeting room and wait','Wait for instructions from the receptionist only','Follow the host employee and evacuation procedures','Leave the building on their own'], a:2, e:'Guests must follow their host employee and all evacuation procedures during any drill or real emergency.' },
];

export const SHEETS_URL = 'https://script.google.com/macros/s/AKfycbx98wFRPtNWSKSckvXZiT6e9_rVF3GW0zXlRZz1chkNKJ9OaVT9_YWd6l6rMm3vyr0h/exec';
export const SUPERVISOR_PIN = '1234';
export const PASS_MARK = 75;
export const TOTAL_SECONDS = 20 * 60;
export const LETTERS = ['A', 'B', 'C', 'D'];
